/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        body: [
          "var(--font-zen-kaku-gothic-new)",
          "Zen Kaku Gothic New",
          "sans-serif",
        ],
        heading: [
          "var(--font-poppins)",
          "Poppins",
          "var(--font-zen-kaku-gothic-new)",
          "Zen Kaku Gothic New",
          "sans-serif",
        ],
        display: [
          "var(--font-poppins)",
          "Poppins",
          "var(--font-zen-kaku-gothic-new)",
          "Zen Kaku Gothic New",
          "sans-serif",
        ],
        headline: [
          "var(--font-poppins)",
          "Poppins",
          "var(--font-zen-kaku-gothic-new)",
          "Zen Kaku Gothic New",
          "sans-serif",
        ],
        mono: [
          "var(--font-ibm-plex-mono)",
          "IBM Plex Mono",
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          "monospace",
        ],
      },
      colors: {
        primary: {
          900: "var(--primary-900)",
          700: "var(--primary-700)",
          500: "var(--primary-500)",
          300: "var(--primary-300)",
          200: "var(--primary-200)",
          100: "var(--primary-100)",
          50: "var(--primary-50)",
        },
        accent: {
          600: "var(--accent-600)",
          500: "var(--accent-500)",
          100: "var(--accent-100)",
        },
        neutral: {
          900: "var(--neutral-900)",
          700: "var(--neutral-700)",
          600: "var(--neutral-600)",
          500: "var(--neutral-500)",
          200: "var(--neutral-200)",
          100: "var(--neutral-100)",
          50: "var(--neutral-50)",
        },
        success: "var(--success)",
        info: "var(--info)",
        warning: "var(--warning)",
        portal: {
          bg: "var(--portal-bg)",
          surface: "var(--portal-surface)",
          "on-surface": "var(--portal-on-surface)",
          "on-surface-variant": "var(--portal-on-surface-variant)",
          "on-surface-card": "var(--portal-on-surface-card)",
          "on-surface-card-sub": "var(--portal-on-surface-card-sub)",
          primary: "var(--portal-primary)",
          "primary-container": "var(--portal-primary-container)",
          "on-primary": "var(--portal-on-primary)",
          "surface-lowest": "var(--portal-surface-lowest)",
          "surface-low": "var(--portal-surface-low)",
          "surface-container": "var(--portal-surface-container)",
          "secondary-container": "var(--portal-secondary-container)",
          "on-secondary-container": "var(--portal-on-secondary-container)",
          outline: "var(--portal-outline)",
          "tertiary-fixed-dim": "var(--portal-tertiary-fixed-dim)",
          "tertiary-container": "var(--portal-tertiary-container)",
          "on-tertiary-container": "var(--portal-on-tertiary-container)",
          error: "var(--portal-error)",
          secondary: "var(--portal-secondary)",
          "nav-bg": "var(--portal-nav-bg)",
          "nav-border": "var(--portal-nav-border)",
        },
      },
      spacing: {
        "space-1": "var(--space-1)",
        "space-2": "var(--space-2)",
        "space-3": "var(--space-3)",
        "space-4": "var(--space-4)",
        "space-6": "var(--space-6)",
        "space-8": "var(--space-8)",
        "space-12": "var(--space-12)",
        "space-16": "var(--space-16)",
        "space-20": "var(--space-20)",
        "space-24": "var(--space-24)",
        "space-32": "var(--space-32)",
        "section-gap": "var(--section-gap)",
      },
      fontSize: {
        hero: "var(--text-hero)",
        h1: "var(--text-h1)",
        h2: "var(--text-h2)",
        h3: "var(--text-h3)",
        body: "var(--text-body)",
        small: "var(--text-small)",
        caption: "var(--text-caption)",
      },
      lineHeight: {
        tight: "var(--leading-tight)",
        normal: "var(--leading-normal)",
        loose: "var(--leading-loose)",
      },
      maxWidth: {
        container: "1120px",
      },
      borderRadius: {
        card: "12px",
      },
    },
  },
  plugins: [],
};
